# Generated by Django 3.0.5 on 2020-04-07 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('colorName', models.CharField(max_length=32)),
                ('colorCode', models.CharField(max_length=16)),
                ('colorHex', models.CharField(default='0xFFFFFFFF', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('focusDescr', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Followspot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('spotType', models.CharField(max_length=32)),
                ('wattage', models.IntegerField(default=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('shotDescr', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SpotCue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('cueLabel', models.CharField(max_length=100)),
                ('pageNumber', models.IntegerField(default=1)),
                ('eosCueNumber', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('operatorNumber', models.IntegerField(default=1)),
                ('operatorName', models.CharField(max_length=64)),
                ('notes', models.CharField(max_length=512)),
                ('followspotType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.Followspot')),
            ],
        ),
        migrations.CreateModel(
            name='ColorFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('index', models.IntegerField(default=1)),
                ('color1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color1', to='lightlineapp.Color')),
                ('color2', models.ForeignKey(default='NC', on_delete=django.db.models.deletion.CASCADE, related_name='color2', to='lightlineapp.Color')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('fadeTime', models.IntegerField(default=3)),
                ('intensity', models.IntegerField(default=100)),
                ('colorFlag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.ColorFlag')),
                ('cue', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.SpotCue')),
                ('focus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.Focus')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.Operator')),
                ('shotType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.Shot')),
            ],
        ),
    ]
