# Generated by Django 3.2.11 on 2022-03-13 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('colorName', models.CharField(max_length=32, unique=True)),
                ('colorCode', models.CharField(max_length=16)),
                ('colorHex', models.CharField(default='0xFFFFFFFF', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Cue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('cueLabel', models.CharField(blank=True, default='', max_length=100)),
                ('pageNumber', models.IntegerField(default=1)),
                ('eosCueNumber', models.IntegerField(default=1)),
                ('cueTime', models.IntegerField(default=5)),
                ('cueDescription', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CueList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('listName', models.CharField(max_length=64)),
                ('cueListNumber', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Followspot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('spotType', models.CharField(max_length=32)),
                ('wattage', models.IntegerField(default=3000)),
                ('available', models.IntegerField(default=1)),
                ('dimmerControlled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.URLField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('showName', models.CharField(max_length=64)),
                ('showNameShort', models.CharField(default='', max_length=32)),
                ('active', models.BooleanField(default=False)),
                ('lightingDesigner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('shotDescr', models.CharField(max_length=32)),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('operatorNumber', models.IntegerField(default=1)),
                ('operatorName', models.CharField(max_length=64)),
                ('followspotType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.followspot')),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('headerTitle', models.CharField(blank=True, default='', max_length=100)),
                ('cue', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.cue')),
                ('cueList', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.cuelist')),
            ],
        ),
        migrations.AddField(
            model_name='followspot',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.project'),
        ),
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('focusDescr', models.CharField(max_length=32, unique=True)),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.project')),
            ],
        ),
        migrations.AddField(
            model_name='cuelist',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.project'),
        ),
        migrations.AddField(
            model_name='cue',
            name='cueList',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.cuelist'),
        ),
        migrations.CreateModel(
            name='ColorFlag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('index', models.IntegerField(default=1)),
                ('color1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color1', to='lightlineapp.color')),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('fadeTime', models.IntegerField(default=3)),
                ('intensity', models.IntegerField(default=100)),
                ('colorFlag', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.colorflag')),
                ('cue', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.cue')),
                ('focus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.focus')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.operator')),
                ('shotType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.shot')),
            ],
        ),
    ]
