# Generated by Django 3.0.5 on 2020-04-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightlineapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Lighting Designer'), (2, 'Assistant'), (3, 'Associate'), (4, 'Master Electrician'), (5, 'Electrician'), (6, 'Followspot Operator'), (7, 'Stage Manager')], null=True),
        ),
    ]
