# Generated by Django 3.2.11 on 2022-03-13 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lightlineapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accessoryName', models.CharField(max_length=32, unique=True)),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Breakout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('circuitLabel', models.CharField(max_length=32, unique=True)),
                ('service', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cableLabel', models.CharField(max_length=32, unique=True)),
                ('cableType', models.CharField(max_length=16, unique=True)),
                ('cableLength', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CableType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cableTypeName', models.CharField(max_length=32, unique=True)),
                ('weightPerFoot', models.IntegerField()),
                ('ampRating', models.IntegerField()),
                ('power', models.BooleanField(default=False)),
                ('data', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('circuitLabel', models.CharField(max_length=32, unique=True)),
                ('service', models.IntegerField()),
                ('breakout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.breakout')),
            ],
        ),
        migrations.CreateModel(
            name='FocusChart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chartLabel', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Gobo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('goboName', models.CharField(max_length=32, unique=True)),
                ('goboCode', models.CharField(max_length=16, unique=True)),
                ('imageUrl', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('positionName', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='color',
            name='colorCode',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.CreateModel(
            name='InstrumentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('typeName', models.CharField(max_length=64)),
                ('load', models.IntegerField()),
                ('beamAngle', models.IntegerField()),
                ('fieldAngle', models.IntegerField()),
                ('zoomAngleMin', models.IntegerField()),
                ('zoomAngleMax', models.IntegerField()),
                ('zoomAble', models.BooleanField(default=False)),
                ('weight', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unitNumber', models.IntegerField()),
                ('goboSize', models.CharField(max_length=8)),
                ('purpose', models.CharField(max_length=128, unique=True)),
                ('dimmer', models.IntegerField()),
                ('dimmerPhase', models.CharField(max_length=8)),
                ('address', models.IntegerField()),
                ('universe', models.IntegerField()),
                ('channel', models.IntegerField()),
                ('accessory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.accessory')),
                ('breakout', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.breakout')),
                ('cable', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.cable')),
                ('circuit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.circuit')),
                ('color', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.color')),
                ('focusChart', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.focuschart')),
                ('gobo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.gobo')),
                ('instrumentType', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.instrumenttype')),
                ('position', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.position')),
            ],
        ),
    ]
