# Generated by Django 3.0.5 on 2020-04-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightlineapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followspot',
            name='available',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='followspot',
            name='wattage',
            field=models.IntegerField(default=3000),
        ),
    ]
