# Generated by Django 3.2.11 on 2022-03-13 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lightlineapp', '0002_auto_20220313_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('noteLabel', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='WorkNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('noteLabel', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='instrument',
            name='focusNote',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.focusnote'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='workNote',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.worknote'),
        ),
    ]
