# Generated by Django 3.2.11 on 2022-03-13 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lightlineapp', '0003_auto_20220313_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.accessory'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='address',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='breakout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.breakout'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='cable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.cable'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='channel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='circuit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.circuit'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.color'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='dimmer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='focusChart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.focuschart'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='focusNote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.focusnote'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='gobo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.gobo'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instrumentType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.instrumenttype'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.position'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='universe',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='workNote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.worknote'),
        ),
    ]
