# Generated by Django 3.0.5 on 2020-04-16 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lightlineapp', '0003_project_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorflag',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.Project'),
        ),
        migrations.AddField(
            model_name='focus',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.Project'),
        ),
        migrations.AddField(
            model_name='followspot',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.Project'),
        ),
        migrations.AddField(
            model_name='operator',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.Project'),
        ),
    ]
