# Generated by Django 3.2.11 on 2022-03-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightlineapp', '0004_auto_20220313_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='purpose',
            field=models.CharField(max_length=128),
        ),
    ]
