# Generated by Django 3.0.5 on 2020-04-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightlineapp', '0004_auto_20200415_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuelist',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
