# Generated by Django 3.2.11 on 2022-03-13 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lightlineapp', '0005_alter_instrument_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lightlineapp.project'),
        ),
    ]
