# Generated by Django 3.2.11 on 2022-03-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightlineapp', '0006_instrument_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='dimmerPhase',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='goboSize',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
