# Generated by Django 3.2.11 on 2022-03-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightlineapp', '0007_auto_20220314_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumenttype',
            name='load',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
