# Generated by Django 3.2.11 on 2022-03-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightlineapp', '0011_auto_20220314_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='color',
            field=models.ManyToManyField(blank=True, related_name='colors', to='lightlineapp.Color'),
        ),
    ]
