# Generated by Django 3.2.11 on 2022-03-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightlineapp', '0012_alter_instrument_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gobo',
            name='goboName',
            field=models.CharField(max_length=32),
        ),
    ]
