# Generated by Django 4.0.4 on 2022-04-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worknote',
            name='priority',
            field=models.IntegerField(default=5),
        ),
    ]
