# Generated by Django 4.0.4 on 2022-04-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_worknote_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='worknote',
            name='createdAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
