# Generated by Django 4.0.4 on 2022-04-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_worknote_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worknote',
            name='newPurpose',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='worknote',
            name='newUnitNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
