# Generated by Django 4.0.4 on 2022-04-22 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
        ('notes', '0004_alter_worknote_newpurpose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worknote',
            name='assignedTo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignedTo', to='landing.profile'),
        ),
        migrations.AlterField(
            model_name='worknote',
            name='lastUpdatedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lastUpdatedBy', to='landing.profile'),
        ),
    ]
