# Generated by Django 4.0.4 on 2022-04-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_worknote_assignedto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worknote',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
