# Generated by Django 4.0.4 on 2022-04-22 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectManager', '0001_initial'),
        ('notes', '0006_alter_worknote_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worknote',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectManager.project'),
        ),
    ]
