# Generated by Django 3.0.5 on 2020-04-06 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colorName', models.CharField(max_length=32)),
                ('colorCode', models.CharField(max_length=16)),
                ('colorHex', models.CharField(default='0xFFFFFFFF', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focusDescr', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Followspot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotType', models.CharField(max_length=32)),
                ('wattage', models.IntegerField(default=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shotDescr', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SpotCue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cueLabel', models.CharField(max_length=100)),
                ('pageNumber', models.IntegerField(default=1)),
                ('eosCueNumber', models.IntegerField(default=1)),
                ('lastUpdate', models.DateTimeField(verbose_name='Last updated')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operatorNumber', models.IntegerField(default=1)),
                ('operatorName', models.CharField(max_length=64)),
                ('notes', models.CharField(max_length=512)),
                ('followspotType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followspots.Followspot')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastUpdate', models.DateTimeField(verbose_name='Last updated')),
                ('fadeTime', models.IntegerField(default=3)),
                ('intensity', models.IntegerField(default=100)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followspots.Color')),
                ('cue', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='followspots.SpotCue')),
                ('focus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followspots.Focus')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followspots.Operator')),
                ('shotType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followspots.Shot')),
            ],
        ),
    ]
