# Generated by Django 4.0.3 on 2022-04-17 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projectManager', '0001_initial'),
        ('database', '0001_initial'),
        ('cueList', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followspot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('spotType', models.CharField(max_length=32)),
                ('wattage', models.IntegerField(default=3000)),
                ('available', models.IntegerField(default=1)),
                ('dimmerControlled', models.BooleanField(default=False)),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projectManager.project')),
            ],
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('shotDescr', models.CharField(max_length=32)),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projectManager.project')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('operatorNumber', models.IntegerField(default=1)),
                ('operatorName', models.CharField(max_length=64)),
                ('followspotType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followspots.followspot')),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projectManager.project')),
            ],
        ),
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('focusDescr', models.CharField(max_length=32, unique=True)),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projectManager.project')),
            ],
        ),
        migrations.CreateModel(
            name='ColorFlag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('index', models.IntegerField(default=1)),
                ('color1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color1', to='database.color')),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projectManager.project')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('fadeTime', models.IntegerField(default=3)),
                ('intensity', models.IntegerField(default=100)),
                ('colorFlag', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='followspots.colorflag')),
                ('cue', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cueList.cue')),
                ('focus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followspots.focus')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followspots.operator')),
                ('shotType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followspots.shot')),
            ],
        ),
    ]
