# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-02 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('followspots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='cue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='followspots.SpotCue'),
        ),
    ]
