# Generated by Django 3.0.5 on 2020-04-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followspots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorflag',
            name='boomerang',
        ),
        migrations.RemoveField(
            model_name='followspot',
            name='boomerang',
        ),
        migrations.AddField(
            model_name='colorflag',
            name='index',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Boomerang',
        ),
    ]
