# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-02 02:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followspots', '0002_action_cue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotcue',
            name='color',
        ),
        migrations.RemoveField(
            model_name='spotcue',
            name='fadeTime',
        ),
    ]
