# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-02 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followspots', '0003_auto_20200401_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='intensity',
            field=models.IntegerField(default=100),
        ),
    ]
