# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-02 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followspots', '0004_action_intensity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='colorBlue',
        ),
        migrations.RemoveField(
            model_name='color',
            name='colorGreen',
        ),
        migrations.RemoveField(
            model_name='color',
            name='colorRed',
        ),
        migrations.AddField(
            model_name='color',
            name='colorHex',
            field=models.CharField(default='0xFFFFFFFF', max_length=32),
        ),
    ]
