# Generated by Django 4.0.4 on 2022-04-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='purpose',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='unitNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
